MCU = RP2040
BOOTLOADER = rp2040

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

VIA_ENABLE = yes
VIAL_ENABLE = no
LTO_ENABLE = yes
